variables:
  - template: ci/variables/cfs.yml@eng

trigger:
  branches:
    include:
    # These are the branches we'll mirror to our internal ADO instance
    # Keep this set limited as appropriate (don't mirror individual user branches).
    - main

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      spotBugs:
        enabled: false
    stages:
      - template: ci/code-mirror.yml@eng
