pr: none
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: DurableTaskJavaBuildPipeline
    source: durabletask-java.official

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    stages:
    - stage: release
      jobs:
      - job: durabletask_azuremanaged 
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          # Declare inputs to be released here to ensure they receive relevant checks
          - input: pipelineArtifact
            pipeline: DurableTaskJavaBuildPipeline
            artifactName: drop

        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: 'Release durabletask-azuremanaged'
          inputs:
            connectedservicename: 'dtfx-internal-esrp-prod'
            usemanagedidentity: true
            keyvaultname: 'durable-esrp-akv'
            signcertname: 'dts-esrp-cert'
            clientid: '0b3ed1a4-0727-4a50-b82a-02c2bd9dec89'
            folderlocation: '$(System.DefaultWorkingDirectory)/_durabletask-java.official/drop/durabletask-azuremanaged'
            owners: 'wangbill@microsoft.com'
            approvers: 'kaibocai@microsoft.com'
            mainpublisher: 'durabletask-java'

      - job: durabletask_client
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          # Declare inputs to be released here to ensure they receive relevant checks
          - input: pipelineArtifact
            pipeline: DurableTaskJavaBuildPipeline
            artifactName: drop

        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: 'Release durabletask-client'
          inputs:
            connectedservicename: 'dtfx-internal-esrp-prod'
            usemanagedidentity: true
            keyvaultname: 'durable-esrp-akv'
            signcertname: 'dts-esrp-cert'
            clientid: '0b3ed1a4-0727-4a50-b82a-02c2bd9dec89'
            folderlocation: '$(System.DefaultWorkingDirectory)/_durabletask-java.official/drop/durabletask-client'
            owners: 'wangbill@microsoft.com'
            approvers: 'kaibocai@microsoft.com'
            mainpublisher: 'durabletask-java'

      - job: durabletask_azure_functions
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          # Declare inputs to be released here to ensure they receive relevant checks
          - input: pipelineArtifact
            pipeline: DurableTaskJavaBuildPipeline
            artifactName: drop

        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: 'Release durabletask-azure-functions'
          inputs:
            connectedservicename: 'dtfx-internal-esrp-prod'
            usemanagedidentity: true
            keyvaultname: 'durable-esrp-akv'
            signcertname: 'dts-esrp-cert'
            clientid: '0b3ed1a4-0727-4a50-b82a-02c2bd9dec89'
            folderlocation: '$(System.DefaultWorkingDirectory)/_durabletask-java.official/drop/durabletask-azure-functions'
            owners: 'wangbill@microsoft.com'
            approvers: 'kaibocai@microsoft.com'
            mainpublisher: 'durabletask-java'
